"""Constants for Waveshare RS485-to-ETH integration."""

DOMAIN = "waveshare_rs485toeth"
MANUFACTURER = "Deye"

# Integration version
VERSION = "1.0.0"

# Configuration keys
CONF_GATEWAYS = "gateways"
CONF_GATEWAY_HOST = "host"
CONF_GATEWAY_PORT = "port"
CONF_GATEWAY_TIMEOUT = "timeout"
CONF_GATEWAY_KEEPALIVE = "keepalive"
CONF_DEVICES = "devices"
CONF_DEVICE_NAME = "name"
CONF_DEVICE_SLAVE_ID = "slave_id"
CONF_DEVICE_TYPE = "device_type"
CONF_DEVICE_SCAN_INTERVAL = "scan_interval"

# Default values
DEFAULT_GATEWAY_PORT = 8234
DEFAULT_GATEWAY_TIMEOUT = 10
DEFAULT_GATEWAY_KEEPALIVE = 300
DEFAULT_DEVICE_SCAN_INTERVAL = 30
DEFAULT_RESPONSE_TIME_WARNING = 2000  # ms
DEFAULT_CONSECUTIVE_FAILURES_ERROR = 5
DEFAULT_CONSECUTIVE_FAILURES_OFFLINE = 10

# Modbus settings
MODBUS_FUNCTION_READ_HOLDING_REGISTERS = 3
MODBUS_FUNCTION_READ_INPUT_REGISTERS = 4
MODBUS_FUNCTION_WRITE_SINGLE_REGISTER = 6
MODBUS_FUNCTION_WRITE_MULTIPLE_REGISTERS = 16

# Health states
HEALTH_STATE_HEALTHY = "healthy"
HEALTH_STATE_DEGRADED = "degraded"
HEALTH_STATE_WARNING = "warning"
HEALTH_STATE_ERROR = "error"
HEALTH_STATE_OFFLINE = "offline"

HEALTH_STATES = [
    HEALTH_STATE_HEALTHY,
    HEALTH_STATE_DEGRADED,
    HEALTH_STATE_WARNING,
    HEALTH_STATE_ERROR,
    HEALTH_STATE_OFFLINE,
]

# Error types
ERROR_TYPE_TIMEOUT = "timeout"
ERROR_TYPE_CHECKSUM = "checksum"
ERROR_TYPE_COMMUNICATION = "communication"
ERROR_TYPE_NO_RESPONSE = "no_response"

# Device types
DEVICE_TYPE_DEYE_SUN_12K = "DEYE_SUN_12K"
DEVICE_TYPE_DEYE_SUN_8K = "DEYE_SUN_8K"
DEVICE_TYPE_DEYE_SUN_6K = "DEYE_SUN_6K"
DEVICE_TYPE_DEYE_HYBRID_GW4137 = "DEYE_HYBRID_GW4137"
DEVICE_TYPE_PYTES_EBOX_48100R = "PYTES_EBOX_48100R"
DEVICE_TYPE_GENERIC_MODBUS = "GENERIC_MODBUS"

# Device features
FEATURE_SOLAR = "solar"
FEATURE_BATTERY = "battery"
FEATURE_GRID = "grid"
FEATURE_AC_OUTPUT = "ac_output"

# Register data types
REG_TYPE_UINT16 = "uint16"
REG_TYPE_UINT32 = "uint32"
REG_TYPE_INT16 = "int16"
REG_TYPE_INT32 = "int32"
REG_TYPE_FLOAT = "float"

# Data units
UNIT_POWER_W = "W"
UNIT_VOLTAGE_V = "V"
UNIT_CURRENT_A = "A"
UNIT_ENERGY_KWH = "kWh"
UNIT_TEMPERATURE_C = "°C"
UNIT_FREQUENCY_HZ = "Hz"
UNIT_PERCENTAGE = "%"

# Entity categories
ENTITY_CATEGORY_DIAGNOSTIC = "diagnostic"
ENTITY_CATEGORY_CONFIG = "config"

# Modbus addresses for device detection
MODBUS_DEVICE_ID_ADDRESS = 0x000B  # Typical device ID register

# Service calls
SERVICE_RESET_DAILY_ERRORS = "reset_daily_errors"
SERVICE_RESET_MONTHLY_ERRORS = "reset_monthly_errors"
SERVICE_FORCE_REFRESH = "force_refresh"

# Supported device models
SUPPORTED_DEVICE_MODELS = {
    DEVICE_TYPE_DEYE_SUN_12K: {
        "name": "Deye Sun 12K",
        "features": [FEATURE_SOLAR, FEATURE_BATTERY, FEATURE_GRID],
    },
    DEVICE_TYPE_DEYE_SUN_8K: {
        "name": "Deye Sun 8K",
        "features": [FEATURE_SOLAR, FEATURE_BATTERY, FEATURE_GRID],
    },
    DEVICE_TYPE_DEYE_SUN_6K: {
        "name": "Deye Sun 6K",
        "features": [FEATURE_SOLAR, FEATURE_GRID],
    },
    DEVICE_TYPE_DEYE_HYBRID_GW4137: {
        "name": "Deye Hybrid GW4137",
        "features": [FEATURE_SOLAR, FEATURE_BATTERY, FEATURE_GRID, FEATURE_AC_OUTPUT],
    },
    DEVICE_TYPE_PYTES_EBOX_48100R: {
        "name": "Pytes E-Box 48100R",
        "features": [FEATURE_BATTERY],
    },
    DEVICE_TYPE_GENERIC_MODBUS: {
        "name": "Generic Modbus Device",
        "features": [],
    },
}

# Request scheduling
REQUEST_MIN_DELAY_MS = 100  # Minimum delay between requests on same RS485
MAX_RETRY_ATTEMPTS = 30
RETRY_BACKOFF_START_SEC = 1
RETRY_BACKOFF_MAX_SEC = 8

# Error tracking
ERROR_HISTORY_SIZE = 100
